language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly


before_install:
  - sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots

install:
  - sudo apt-get update -qq
  - sudo apt-get install -q -y libsdl2-dev
